# Generated by Django 3.2.4 on 2021-07-02 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('sale_price', models.CharField(max_length=50)),
                ('sale_period', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('ivory', '아이보리'), ('not-specified', 'Not Specified'), ('black', '블랙')], max_length=80, null=True)),
                ('number', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='team1/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team1.team1')),
            ],
        ),
    ]
